### ISSUE TITLE
Email users that their parking permits will expire

### ISSUE THREAD

**Issue by sortizsh** [cityofaustin/atd-residential-parking-permits#13]
As a user I should receive an email upon expiration of my permits so that I know to renew. 

*Migrated to [atd-data-tech #1592](https://github.com/cityofaustin/atd-data-tech/issues/1592)*

**Comment by dianamartin** [comment]
TEST THIS:
**Email Notifications (6 months before expiration)**
- passive email (email sent just looking at a field ("Permit Expiration Date")
- form submission email (RPP staff, manual click form)

**Comment by dianamartin** [comment]
talked with @johnclary and he said that Knack has a "tasks" function that should be able to read a field and create an email rule to do this.
