### ISSUE TITLE
As RPP staff needs to have the ability to approve or reject resident applications.

### ISSUE THREAD

**Issue by sortizsh** [cityofaustin/atd-residential-parking-permits#31]
As an administrator, I am able to approve or reject resident applications and documentation as a part of the RPP verification process.

*Migrated to [atd-data-tech #1991](https://github.com/cityofaustin/atd-data-tech/issues/1991)*

**Comment by dianamartin** [comment]
Application `Rejected` if the following: 
- User is ineligible to receive RPP permit
- User has reached maximum permit limits for their RPP district
- User's documents provided are not valid (ex. lease is out of date)
