### ISSUE TITLE
RPP staff is able to create accounts on behalf of residents who are requesting assistance.  

### ISSUE THREAD

**Issue by sortizsh** [cityofaustin/atd-residential-parking-permits#33]
As an administrator, I am able to create new accounts so I can help people who, for whatever reason, did not or cannot make an account on their own.

*Migrated to [atd-data-tech #1616](https://github.com/cityofaustin/atd-data-tech/issues/1616)*

**Comment by ghost** [comment]
There are concerns about taking the credit card over the phone and its Payment Card Industry status and standards.  A POS system is a different status then a website status.  Research is needed.  Teri assigned to the research.
