### ISSUE TITLE
Meet to do feature prioritization

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-residential-parking-permits#38]
**Objective** 

- [x] Refine user stories as needed 
- [x] Assign size estimates
- [x] Review Must/Need/Want 

**Participants**
Required
- Diana
- Amenity
- John
- Alyse
- Ryan

Optional
- Teri
- Tracy

**Meeting series**

------
- [x] 4/24 - Teri, Diana, Amenity, Tracy, Alyse, Ryan @ Barton Oaks
- [x] 5/6

**Comment by TracyLinder** [comment]
@amenity A couple of questions..
1. Is this for RPP or?
2. I may have misunderstood; are we not supposed to have more than one team label on an issue?
Thank You!

**Comment by amenity** [comment]
Yup, for RPP! You can tell because it's in the `atd-residential-parking-permits` repo. The exceptions to the one team rule are meetings and epics.

**Comment by TracyLinder** [comment]
You teach me so much. <3
