### ISSUE TITLE
Verify residents using COA utility account number

### ISSUE THREAD

**Issue by sortizsh** [cityofaustin/atd-residential-parking-permits#4]
### As a user I should be able to enter my City of Austin account number to verify residence and identity so that i may obtain an RPP.

Austin Water, Finance, and Austin Energy all have access to COA utilities account data. It would be great to have an integration that would allow us to check a resident's name and address against their database to verify residency. 

*Migrated to [atd-data-tech #1870](https://github.com/cityofaustin/atd-data-tech/issues/1870)*

**Comment by ghost** [comment]
Could we do a stop audit on permits to see if they do have an account number?  I would need about 100 names and addresses and I will run it by AW.  Let's just see if it is going to be an issue or not.

**Comment by amenity** [comment]
Great idea!
