### ISSUE TITLE
Get information about current City payment arrangements and future plans

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-residential-parking-permits#41]
Meet with Mark Caraway to learn about the City's current payment processing technologies/processes and their future plans and timeline.

**Comment by ghost** [comment]
Ok

**Comment by amenity** [comment]
From Bob Bell at Austin Public Library. (He's the one who implemented and runs the library fee collection with Chase Connexion.)

**How was it for you to set up initially and then maintain?**
- It was a long (more than year long journey), but that included various citywide functions, which may be streamlined now.  
- We had to stand up hardware and software in City DMZ, which involved CTM and CTM Security giving the blessing every step of the way, because of the potential PCI Compliance issues.    
- There were official CTM Project Management involved, which was rather onerous (from a developers/integrators point of view) at some point, but we muddled through. 
- There was Chase deployment methodologies and setup that required this CTM Project Management, and contractual agreements and integration with Finance and Treasury that were highly technical, but everyone performed well and timely for the most part.
- The tricky parts are setting up the round trip processes. We create City side transactions from authenticated users who select fines that they wish to pay, then we transfer control over to Chase, they process the credit cards without us every storing any PCI information, then Chase makes call back to our COA DMZ servers indicating taking payment for the transaction, then our side applies the transaction to our systems. The only information passed to Chase is our Patrons library card, session token, payment transaction id, and amount. 

**I noticed that the form linked to from [their demo site](https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.payconnexion.com%2Fdemo%2Findex.html&data=02%7C01%7CAmenity.Applewhite%40austintexas.gov%7Cffca7942a7c14e5431ea08d6da1b9ddb%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C636936209473442726&sdata=WEK0g7%2FKgbVRuh3Kq6iGi3UgkyyhrAdASbZkU8mGFVA%3D&reserved=0) has numerous accessibility errors. Can anything be done to remediate that?** 
- I do not know.  

**Do residents generally find it easy to use?**
- There are about $80,000.00 year payments made through it, and I have not heard major complaints from public, but there are some APL Finance reconciliation processes that can be complicated, and challenging to troubleshoot sometime, but not very frequently do we have issues.  Like, when Chase receives a Payment, but we were not successful in applying to our patrons fines.   Generally, if you setup the Procedures for handling these exceptions, front line staff can get them resolved fairly quickly. There are always people who generally want things to work they want them to, and will complain, but I get the feeling it is generally easy enough to use for them. No official, usability studies have been done, or surveys to find out. 😄 

**Are there any features or drawbacks we should be aware of?** 
- There are features that I am sure we did not take advantage of, as our initial setup was only to pay Library Fines (one single product code) and deposit this directly into our General Fund.   
- I think we should have setup additional Features, like Donations/Gifts to the library and had Finance create the necessary deposit accounts, because in order to now embark on that venture, we would have to setup another whole project and go through it all again, which makes us hesitate at the moment.

**Comment by ghost** [comment]
Great info!  See comments below


________________________________

**Comment by amenity** [comment]
Duplicate of #60.
