### ISSUE TITLE
Reach out to Austin Energy(?) to find out about using COA utilities credentials

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-residential-parking-permits#44]
- [ ] Inquire with Heather Turner (DM, AE utilities credentials)

*Migrated to [atd-data-tech #1589](https://github.com/cityofaustin/atd-data-tech/issues/1589)*

**Comment by amenity** [comment]
@teripennington - Am I remembering correctly that you knew someone we could talk to about this?

**Comment by ghost** [comment]
Talked with Greg Flay today. He's sending me a form for our requests to be officially evaluated. There are 4 options: Add permits to CCnB (this would take a long time and we might want to consider it for the future), hit CCnB directly (form), hit AW and get permission from AE (form), and use CCnB credentials (form).

**Comment by amenity** [comment]
What is CCnB?
