### ISSUE TITLE
Set up Meeting to assess staff costs of current process (OLD process)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-residential-parking-permits#46]
Average costs per hour
How much time spent on tasks

Meeting Attendees: 
- Teri
- Ryan
- Alyse

**Comment by dianamartin** [comment]
Time permitting: discuss start to finish metric at this meeting. If topic is covered, close other issue #47

**Comment by ghost** [comment]
Met with Alyse and Ryan. We have a beginning cost model with staff time for each of the steps in the current process. I will setup a meeting with mgt to review this model.
