### ISSUE TITLE
Review RPP cost model 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-residential-parking-permits#47]
Review [RPP Cost Model](https://cityofaustin-my.sharepoint.com/:x:/r/personal/teri_pennington_austintexas_gov1/_layouts/15/Doc.aspx?sourcedoc=%7Bd1b0bd91-b074-43d5-bad7-1b2bff21aaff%7D&action=default&uid=%7BD1B0BD91-B074-43D5-BAD7-1B2BFF21AAFF%7D&ListItemId=6&ListId=%7B3C885C7A-F743-48E1-89D4-7F58EB4E6E5C%7D&odsp=1&env=prod&cid=b6e2fa39-ec81-4179-9348-ae865889aa10) put together during #46. 

Date: 5/28/19
Attendees: Alyse, Ryan, Amenity, Joseph, Teri

Notes:
 - Last time Joseph ran a cost model, total cost to ATD was $170k, got it down to $35k after Ryan was hired, now back to $170k
 - Added enforcement costs — officers, CSR calls, ATD dispatch who answers the phone at the Parking office

**Comment by ghost** [comment]
Met with Alyse and Ryan.  We have a beginning cost model with staff time for each of the steps in the current process.  I will setup a meeting with mgt to review this model.

**Comment by amenity** [comment]
[RPP Cost Model](https://cityofaustin-my.sharepoint.com/:x:/r/personal/teri_pennington_austintexas_gov1/_layouts/15/Doc.aspx?sourcedoc=%7Bd1b0bd91-b074-43d5-bad7-1b2bff21aaff%7D&action=default&uid=%7BD1B0BD91-B074-43D5-BAD7-1B2BFF21AAFF%7D&ListItemId=6&ListId=%7B3C885C7A-F743-48E1-89D4-7F58EB4E6E5C%7D&odsp=1&env=prod&cid=b6e2fa39-ec81-4179-9348-ae865889aa10).
