### ISSUE TITLE
Document data model

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-residential-parking-permits#51]
Tables, fields, field types, and relationships. 

A few of the fields we've discussed including:
Resident/user table
- [ ] Other household member names

*Migrated to [atd-data-tech #1945](https://github.com/cityofaustin/atd-data-tech/issues/1945)*

**Comment by ghost** [comment]
If we purchase a permitting application, we still need to define the mandatory fields.
Prototype contains Transportation data dictionary

**Comment by ghost** [comment]
Need a field for replacement hangtags - in order to track the number of replacements given.  Helps track abusers of the process.
