### ISSUE TITLE
Check with AE about restrictions on the use of COA utilities data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-residential-parking-permits#56]
*Migrated to [atd-data-tech #1848](https://github.com/cityofaustin/atd-data-tech/issues/1848)*

**Comment by ghost** [comment]
Talked with Greg Flay today.  He's sending me a form for our requests to be officially evaluated.  There are 4 options:  Add permits to CCnB (this would take a long time and we might want to consider it for the future), hit CCnB directly (form), hit AW and get permission from AE (form), and use CCnB credentials (form).
