### ISSUE TITLE
Get information on requirements for Knack <--> Austin Water database connection

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-residential-parking-permits#57]

**Comment by ghost** [comment]
AW is amenable.  I must check with AE about permission.  I also need to know how the connection from outside the firewall is made to an internal resource.  I believe it is going through Datapower but Diana is checking.

**Comment by ghost** [comment]
Checked with AE, there is a form to be filled out and then they will let us know.

**Comment by ghost** [comment]
Form submitted to AE.  
If we use the AW data warehouse, the connection would be through datapower ESB in the DMZ and the Linux box hosted by CTM.
