### ISSUE TITLE
Confirmation email of submitted application to user

### ISSUE THREAD

**Issue by sortizsh** [cityofaustin/atd-residential-parking-permits#6]
H:  As user,  I will receive an automated email when I submit an application so that I will know the status of my application. 

*Migrated to [atd-data-tech #1739](https://github.com/cityofaustin/atd-data-tech/issues/1739)*

**Comment by dianamartin** [comment]
- [ ] All fields on application? (see level of effort)
- [ ] List of attachment names
- [ ] Mailing address and approximate ETA of 2 weeks 
>(Approval may take up to 7 business days: but typically turn around in 2 business day depending on volume)
>(4 to 10 business days after approval, not submission)
