### ISSUE TITLE
Find out what payment methods we need to accept

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-residential-parking-permits#66]
Cash? Check? 

There are equity issues in requiring residents to have a bank account in order to access City services.  

Additionally, there are a currently a few RPP customers who insist on paying by check. 

This will determine what the level of need is for #64 and #65.

**Comment by ghost** [comment]
There is no legal or policy requirements to take cash or check.

**Comment by amenity** [comment]
👍
