### ISSUE TITLE
Ask John about Knack integration with other applications/databases

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-residential-parking-permits#68]
Teri had asked me to follow-up to see how Knack "pulls" data from other database sources (i.e. When we pulled data from the Advantage 3 database). 

I believe it is because we want some clarification on how it is done.

**Comment by dianamartin** [comment]
@johnclary Can you explain how we were able to integrate and pull data from the Advantage 3 database when we referenced those "commodity, object, etc.." numbers into the Finance and Purchasing Knack application. 

Did you need special permission, were you able to just use an end point or you knew of an existing API? 

I know you've written scripts to push/pull data from other sources (Socrata, ArcGIS Online, KITS and many others) Teri is trying to get a sense of how we might interact with the data that Austin Energy/Water may share with us. Perhaps giving her an understanding before she can talk to them to request certain things if we are given the "green light" to use their data to valid customer addresses.

**Comment by johnclary** [comment]
Hey, just saw this. We integrate knack with other systems by creating a custom ETL service that runs on our Python server. Typically we do this by (1) querying data from the 3rd party database (SQL, REST, XML, whatever), (2) transforming it as needed, and (3) loading it into Knack using their HTTP API.

**Comment by dianamartin** [comment]
@teripennington: See John's comment on this issue about how Knack integrates with other database systems.

@johnclary: Thanks for the clarification

**Comment by ghost** [comment]
Where is the python server? with knack, DMZ, internal to the city?

**Comment by dianamartin** [comment]
@johnclary : Teri wants to know where the Python server is. 

@teripennington: My understanding is that we have a Linux Virtual Machine and the we have a separate Knack Proxy Server set-up using Flask. 

See my workflow that I created showing the process (per John's guidance)
[CSR_311_to_KNACK_workflow.pdf](https://github.com/cityofaustin/atd-residential-parking-permits/files/3242072/CSR_311_to_KNACK_workflow.pdf)

**Comment by ghost** [comment]
python server is internal to COA's network.

**Comment by ghost** [comment]
close
