### ISSUE TITLE
Metrics for Dispatch for RPP cost model

### ISSUE THREAD

**Issue by ghost** [cityofaustin/atd-residential-parking-permits#72]
Find out how much of the time dispatch is going for RPP calls for the cost model.

**Comment by ghost** [comment]
They are using Trello and there are no metrics.  I have access to the trello data and will count the categories for 3 months to get a sense of the use.  So far, I noticed that the data varies according to who is in dispatch and there is not entries for evening or weekend dispatches.

**Comment by amenity** [comment]
@teripennington's work on this [here](https://teams.microsoft.com/_#/xlsx/viewer/teams/https:~2F~2Fcityofaustin.sharepoint.com~2Fsites~2FResidentialParkingPermitApplication~2FShared%20Documents~2FGeneral~2FPhase%20II~2FCost%20model~2FRPP%20cost%20model.xlsx?threadId=19:e3597e8949f8488c961b78460a886d45@thread.skype&baseUrl=https:~2F~2Fcityofaustin.sharepoint.com~2Fsites~2FResidentialParkingPermitApplication&fileId=01D8FE20-840D-4944-A61F-0CEC71D73503&ctx=files&viewerAction=view).
