### ISSUE TITLE
311 data for RPP enforcement for the cost model

### ISSUE THREAD

**Issue by ghost** [cityofaustin/atd-residential-parking-permits#73]
Requesting 311 data for RPP and the cost model.  ATD spends $498,000 per year on 311.  So how much of that is RPP.

**Comment by amenity** [comment]
Included in [RPP Cost Model](https://teams.microsoft.com/_#/xlsx/viewer/teams/https:~2F~2Fcityofaustin.sharepoint.com~2Fsites~2FResidentialParkingPermitApplication~2FShared%20Documents~2FGeneral~2FPhase%20II~2Fcost%20model~2FRPP%20cost%20model.xlsx?threadId=19:e3597e8949f8488c961b78460a886d45@thread.skype&baseUrl=https:~2F~2Fcityofaustin.sharepoint.com~2Fsites~2FResidentialParkingPermitApplication&fileId=01D8FE20-840D-4944-A61F-0CEC71D73503&ctx=files&viewerAction=view).
